"""usage quota

Revision ID: 8fd873d589e1
Revises: 3a0cf14c58cf
Create Date: 2026-09-12 00:13:51.906640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd873d589e1'
down_revision: Union[str, None] = '3a0cf14c58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_limits',
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('monthly_trend_research', sa.Integer(), nullable=True),
    sa.Column('monthly_agent_ask_deep', sa.Integer(), nullable=True),
    sa.Column('monthly_messenger_sync', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('plan')
    )
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'period', 'job_type', name='uq_usage_counters_team_period_type')
    )
    # ### end Alembic commands ###

    # Limitler koddan değil veriden okunur (Mimari doc bölüm 5) — deploy gerektirmeden değiştirilebilir.
    plan_limits = sa.table(
        'plan_limits',
        sa.column('plan', sa.String),
        sa.column('monthly_trend_research', sa.Integer),
        sa.column('monthly_agent_ask_deep', sa.Integer),
        sa.column('monthly_messenger_sync', sa.Integer),
    )
    op.bulk_insert(
        plan_limits,
        [
            {
                'plan': 'free',
                'monthly_trend_research': 5,
                'monthly_agent_ask_deep': 3,
                'monthly_messenger_sync': None,
            },
            {
                'plan': 'pro',
                'monthly_trend_research': 50,
                'monthly_agent_ask_deep': 30,
                'monthly_messenger_sync': None,
            },
            {
                'plan': 'team',
                'monthly_trend_research': 200,
                'monthly_agent_ask_deep': 100,
                'monthly_messenger_sync': None,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_counters')
    op.drop_table('plan_limits')
    # ### end Alembic commands ###
